services:
  - type: web
    name: Calculatrice-ui
    runtime: static
    buildCommand: cd CalculatriceUi && npm install && npm run build
    staticPublishPath: CalculatriceUi/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html